# Setup the environment for producing the results in the paper
# Activate the environment to run your code using "source activate my-paper"
# or "activate my-paper" on Windows.

name: template-environment
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - pip
    - pandas=1.0.0
    - numpy=1.18.1
    - matplotlib=3.1.3
    - seaborn=0.10.0
    - sklearn=0.22.1
    - pip:
        - ema_workbench==2.0.6
        - SALib==1.3.8
